# Generated by Django 3.0.11 on 2021-06-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ortophoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='ortophoto/pictures', verbose_name='Ortofoto')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', models.BooleanField(default=False, verbose_name='Indice NDVI')),
                ('ndvi_photo', models.FileField(blank=True, null=True, upload_to='ortophoto/pictures/ndvi', verbose_name='NDVI foto')),
                ('crops', models.IntegerField(default=0, verbose_name='Conteo de objetos')),
                ('crops_csv', models.CharField(blank=True, max_length=150, null=True, verbose_name='CSV Coordendas')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ortophotos.Ortophoto', verbose_name='Ortofoto')),
            ],
        ),
    ]
